import React, { useState, useEffect } from "react";
import { syncCollection, saveDocument, deleteDocument } from "../lib/firebase";
import {
  GraduationCap,
  Award,
  BookOpen,
  UploadCloud,
  CheckCircle2,
  Clock,
  ArrowRight,
  ChevronRight,
  AlertTriangle,
  FileText,
  Sparkles,
  Plus,
  Users,
  Search,
  Download,
  Send,
  Trash2,
  Play,
  X,
  FileUp
} from "lucide-react";
import { UserRole, TrainingCourse, TrainingAssignment } from "../types";

interface TrainingHubProps {
  theme: "light" | "dark";
  activeRole: UserRole;
  currentUser: any;
  triggerBannerAlert: (msg: string) => void;
}

// Initial pre-loaded courses to seed the simulator
const INITIAL_COURSES: TrainingCourse[] = [
  {
    id: "course-1",
    title: "Phishing Tactics & Social Engineering Defense",
    description: "Learn to identify modern spear-phishing, spoofed headers, malicious attachments, and urgent social engineering manipulation vectors.",
    category: "PHISHING",
    estimatedMinutes: 10,
    content: "### MODULE 1: Identifying Phishing Requests\nPhishing remains the #1 initial entry vector for cyber attackers. High-profile threats leverage sophisticated domain spoofing and psychological urgency to bypass standard secure firewalls.\n\n### MODULE 2: Visual Indicators of a Spoofed Message\nAlways scrutinize:\n- **Sender Envelope mismatch**: The displayed name doesn't match the actual SMTP sender header domain (e.g., 'Google IT <it-support@service-google-security.net>').\n- **Urgency Hooks**: Phrases like 'Your account is scheduled for deletion within 2 hours' or 'Confidential executive directive' trigger bypass of critical logic.\n- **Unsolicited attachments**: Never execute compressed archives (.zip, .rar) or scripts disguised as invoices (.xlsx.exe).\n\n### MODULE 3: Core Defense Protocol\nWhen suspicious, do NOT click the link. Use the 'Report Phishing' client plugin immediately to quarantine the message in the SIEM ingestion pipeline. If you did click, disconnect your network interface and report to SOC.",
    quiz: [
      {
        question: "What is the very first action you should take upon encountering a suspicious, high-urgency email?",
        options: [
          "Click the attachment in a sandbox or isolated browser to verify if it is safe",
          "Forward the email immediately to all your coworkers to warn them",
          "Refrain from clicking any links, and utilize the 'Report Phishing' plugin to alert the SOC",
          "Reply to the sender demanding they authenticate themselves with certificates"
        ],
        correctIndex: 2
      },
      {
        question: "An email claims to be from executive management demanding urgent, wire transfer validation. How do you verify?",
        options: [
          "Validate by replying directly to that email",
          "Use an out-of-band communication channel (e.g. call or slack) to verify with the executive",
          "Process the transfer because it came from a manager",
          "Assume it is authentic if the sender name display matches exactly"
        ],
        correctIndex: 1
      },
      {
        question: "Which file extension is most dangerous when received as an email attachment?",
        options: [
          "document.pdf",
          "report_archive.zip.exe",
          "invoice.csv",
          "manual_v2.docx"
        ],
        correctIndex: 1
      }
    ]
  },
  {
    id: "course-2",
    title: "MFA Hygiene & Advanced Credential Security",
    description: "Master multi-factor authentication rules, secure vault password managers, and how to avoid session token hijacking.",
    category: "MFA",
    estimatedMinutes: 15,
    content: "### MODULE 1: Multi-Factor Authentication (MFA) Core Pillars\nMFA acts as the absolute baseline gatekeeper. Even if an attacker obtains your username and master password via database leak, MFA blocks lateral system movement.\n\n### MODULE 2: Defending against MFA Fatigue/Push Spam\n- **MFA Fatigue Attacks**: Attackers send repeated push notifications to your phone in quick succession (e.g., at 3:00 AM) hoping you will click 'Approve' just to silence it.\n- **Protocol**: If you receive a push authorization prompt that you did not trigger, select 'DENY & REPORT' instantly. This automatically locks the active user token and forces a reset.\n\n### MODULE 3: Password Manager Best Practices\n- Never reuse passwords across portals.\n- Passwords should be long, randomized strings generated by an official company Password Manager.\n- Secure your browser session; do not store master credentials in unsecured .txt files or post-it notes.",
    quiz: [
      {
        question: "What should you do if you receive consecutive push MFA authorization requests on your mobile phone that you did not initiate?",
        options: [
          "Approve it because it could be a system automation check",
          "Deny it and ignore the notification",
          "Select 'DENY & REPORT' immediately to quarantine your credentials and lock the session",
          "Turn off your phone to avoid getting notifications"
        ],
        correctIndex: 2
      },
      {
        question: "Why is saving password credentials directly in web browser local auto-fill databases discouraged?",
        options: [
          "Web browsers don't encrypt any stored credentials",
          "Session stealer malware can target browser profile directories and extract the master database key",
          "Web browsers do not support multi-factor authentication",
          "It makes typing passwords too slow"
        ],
        correctIndex: 1
      },
      {
        question: "What constitutes a 'strong' password policy under modern SOC-2 directives?",
        options: [
          "At least 6 characters with one capitalization",
          "A simple phrase with a number, changed every month",
          "A long, randomized, machine-generated passphrase unique to each individual service",
          "Any dictionary word with '@' added to the end"
        ],
        correctIndex: 2
      }
    ]
  },
  {
    id: "course-3",
    title: "SOC-2 Audits: Evidence Collection & Data Classification",
    description: "Understand the core Trust Services Criteria (Security, Confidentiality, Availability) and our roles during corporate evidence audits.",
    category: "COMPLIANCE",
    estimatedMinutes: 12,
    content: "### MODULE 1: What is a SOC-2 Audit?\nA Service Organization Control (SOC-2) audit validates our security practices against AICPA guidelines. It is an objective evaluation of whether our security systems are designed to safeguard user tenant data.\n\n### MODULE 2: Security & Privacy Principles\nData must be classified strictly based on sensitivity:\n1. **Public**: Safe for standard marketing and public disclosure.\n2. **Internal Only**: Internal communications, wiki entries, non-sensitive telemetry.\n3. **Restricted**: API Keys, financial sheets, client contracts.\n4. **Critical / Confidential**: User passwords, customer private metadata (PST), decryption keys.\n\n### MODULE 3: Your Role in Evidence Collection\nDuring active audits, you must compile immutable proof of controls, including screenshot capture of MFA enforcement, database encryption flags, access log validation reports, and code change control PR approvals. Never modify historic audit trail logs.",
    quiz: [
      {
        question: "Which of the following belongs in the 'Confidential / Critical' data classification category?",
        options: [
          "General company marketing brochures",
          "Internal system logs and CPU performance indicators",
          "User master passwords and encryption private key files",
          "Standard office directory list"
        ],
        correctIndex: 2
      },
      {
        question: "During a SOC-2 audit, what is the role of 'Evidence Verification'?",
        options: [
          "Providing written claims that systems are secure without proof",
          "Providing objective, verifiable screenshots, configurations, or system logs showing controls are active",
          "Erasing old system error history to present a perfect report",
          "Hiring third-party actors to pass penetration scans"
        ],
        correctIndex: 1
      },
      {
        question: "Under the Trust Services Criteria, what does 'Confidentiality' verify?",
        options: [
          "That the web application has 99.9% uptime",
          "That data designated as confidential is restricted from unauthorized access throughout its lifecycle",
          "That the software code is closed-source",
          "That employees are barred from speaking about their jobs"
        ],
        correctIndex: 1
      }
    ]
  }
];

// Seed initial assignments for mock employees to make the platform lively
const INITIAL_ASSIGNMENTS: TrainingAssignment[] = [
  {
    id: "assign-1",
    courseId: "course-1",
    courseTitle: "Phishing Tactics & Social Engineering Defense",
    assignedToUser: "Sarah Jenkins (Marketing Director)",
    assignedToRole: "ALL",
    status: "COMPLETED",
    completedAt: "2026-07-09 14:22",
    quizScore: "3/3 (100%)"
  },
  {
    id: "assign-2",
    courseId: "course-1",
    courseTitle: "Phishing Tactics & Social Engineering Defense",
    assignedToUser: "Michael Chen (Database Engineer)",
    assignedToRole: "SecEngineer",
    status: "PENDING"
  },
  {
    id: "assign-3",
    courseId: "course-2",
    courseTitle: "MFA Hygiene & Advanced Credential Security",
    assignedToUser: "Elena Rostova (Compliance Analyst)",
    assignedToRole: "ComplianceOfficer",
    status: "IN_PROGRESS"
  },
  {
    id: "assign-4",
    courseId: "course-3",
    courseTitle: "SOC-2 Audits: Evidence Collection & Data Classification",
    assignedToUser: "Auditor Jones (External Assessor)",
    assignedToRole: "Auditor",
    status: "COMPLETED",
    completedAt: "2026-07-08 09:11",
    quizScore: "3/3 (100%)"
  }
];

export default function TrainingHub({
  theme,
  activeRole,
  currentUser,
  triggerBannerAlert
}: TrainingHubProps) {
  const isLight = theme === "light";

  // State managers with offline cache
  const [courses, setCourses] = useState<TrainingCourse[]>(() => {
    const saved = localStorage.getItem("infoshield_courses");
    return saved ? JSON.parse(saved) : INITIAL_COURSES;
  });

  const [assignments, setAssignments] = useState<TrainingAssignment[]>(() => {
    const saved = localStorage.getItem("infoshield_assignments");
    return saved ? JSON.parse(saved) : INITIAL_ASSIGNMENTS;
  });

  // Sync courses with Firestore Collection
  useEffect(() => {
    const unsubscribe = syncCollection<TrainingCourse>(
      "infoshield_courses",
      (items) => {
        setCourses(items);
        localStorage.setItem("infoshield_courses", JSON.stringify(items));
      },
      courses.length > 0 ? courses : INITIAL_COURSES
    );
    return () => unsubscribe();
  }, []);

  // Sync assignments with Firestore Collection
  useEffect(() => {
    const unsubscribe = syncCollection<TrainingAssignment>(
      "infoshield_assignments",
      (items) => {
        setAssignments(items);
        localStorage.setItem("infoshield_assignments", JSON.stringify(items));
      },
      assignments.length > 0 ? assignments : INITIAL_ASSIGNMENTS
    );
    return () => unsubscribe();
  }, []);

  // Navigation sub-tab inside Training Hub
  const [activeSubTab, setActiveSubTab] = useState<"my-courses" | "catalog" | "campaigns">("my-courses");

  // Interactive Course Player State
  const [activeCourseToPlay, setActiveCourseToPlay] = useState<TrainingCourse | null>(null);
  const [currentQuizAnswers, setCurrentQuizAnswers] = useState<number[]>([]);
  const [quizSubmitted, setQuizSubmitted] = useState(false);
  const [quizScore, setQuizScore] = useState(0);

  // Course Upload Form State
  const [uploadTitle, setUploadTitle] = useState("");
  const [uploadCategory, setUploadCategory] = useState<TrainingCourse["category"]>("PHISHING");
  const [uploadMinutes, setUploadMinutes] = useState(10);
  const [uploadDescription, setUploadDescription] = useState("");
  const [uploadContent, setUploadContent] = useState("");
  const [uploadedFile, setUploadedFile] = useState<{ name: string; size: string } | null>(null);
  const [dragActive, setDragActive] = useState(false);

  // Form custom quiz question creators
  const [customQuestion, setCustomQuestion] = useState("Under InfoShield protocols, what is the safest action when a device is compromised?");
  const [customOptions, setCustomOptions] = useState(["Isolate from network immediately", "Restart the server", "Delete browser cache", "Call executive support"]);
  const [correctOptionIndex, setCorrectOptionIndex] = useState(0);

  // Assignment creation Form state
  const [assignCourseId, setAssignCourseId] = useState("");
  const [assignUser, setAssignUser] = useState("");
  const [assignRole, setAssignRole] = useState<UserRole | "ALL" | "">("ALL");

  // Certificate Modal State
  const [selectedCertificateAssign, setSelectedCertificateAssign] = useState<TrainingAssignment | null>(null);



  // Is Admin helper
  const isAdmin = activeRole === "CISO" || activeRole === "SecEngineer" || activeRole === "ComplianceOfficer";

  // Calculate training KPI dashboard analytics
  const totalAssigned = assignments.length;
  const completedCount = assignments.filter(a => a.status === "COMPLETED").length;
  const trainingComplianceRate = totalAssigned > 0 ? Math.round((completedCount / totalAssigned) * 100) : 100;

  // Handle mock file upload
  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") {
      setDragActive(true);
    } else if (e.type === "dragleave") {
      setDragActive(false);
    }
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);

    if (e.dataTransfer.files && e.dataTransfer.files[0]) {
      const file = e.dataTransfer.files[0];
      const sizeKB = Math.round(file.size / 1024);
      setUploadedFile({
        name: file.name,
        size: `${sizeKB} KB`
      });
      triggerBannerAlert(`Successfully analyzed corporate asset file: ${file.name} (${sizeKB} KB)`);
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    if (e.target.files && e.target.files[0]) {
      const file = e.target.files[0];
      const sizeKB = Math.round(file.size / 1024);
      setUploadedFile({
        name: file.name,
        size: `${sizeKB} KB`
      });
      triggerBannerAlert(`Target material cataloged: ${file.name}`);
    }
  };

  // Submit and save new uploaded course
  const handleCreateCourse = (e: React.FormEvent) => {
    e.preventDefault();
    if (!uploadTitle.trim() || !uploadContent.trim()) {
      triggerBannerAlert("Please provide a Title and Training Content for the course.");
      return;
    }

    const newCourseId = `course-custom-${Date.now()}`;
    const newCourse: TrainingCourse = {
      id: newCourseId,
      title: uploadTitle,
      description: uploadDescription || `Security Awareness training covering corporate ${uploadCategory.toLowerCase()} protocols.`,
      category: uploadCategory,
      estimatedMinutes: Number(uploadMinutes) || 10,
      content: uploadContent,
      materialUrl: uploadedFile ? uploadedFile.name : undefined,
      uploadedBy: currentUser ? currentUser.name : "InfoShield Admin",
      quiz: [
        {
          question: customQuestion,
          options: [...customOptions],
          correctIndex: correctOptionIndex
        },
        {
          question: "How should employees verify urgent security policy change alerts?",
          options: [
            "Assume any communication requesting code injection is authentic",
            "Cross-verify the security directive inside the official InfoShield dashboard or GRC settings tab",
            "Disregard security alerts completely",
            "Forward policy changes to open public channels"
          ],
          correctIndex: 1
        },
        {
          question: "Which represents the core objective of Information Security Awareness campaigns?",
          options: [
            "Penalizing employees for honest mistakes",
            "Fostering an alert, defensive work culture that flags and mitigates risks proactively",
            "Increasing network latency through excessive logging",
            "Enforcing zero passwords"
          ],
          correctIndex: 1
        }
      ]
    };

    setCourses(prev => [...prev, newCourse]);
    saveDocument("infoshield_courses", newCourse.id, newCourse);

    // Automatically create a pending assignment for ALL active roles so it shows up
    const autoAssignment: TrainingAssignment = {
      id: `assign-custom-${Date.now()}`,
      courseId: newCourseId,
      courseTitle: uploadTitle,
      assignedToUser: `${currentUser?.name || "Active Session Admin"} (Self)`,
      assignedToRole: "ALL",
      status: "PENDING"
    };
    setAssignments(prev => [autoAssignment, ...prev]);
    saveDocument("infoshield_assignments", autoAssignment.id, autoAssignment);

    triggerBannerAlert(`Successfully published custom security module: "${uploadTitle}". Seeded pending training campaign.`);
    
    // Reset Form
    setUploadTitle("");
    setUploadDescription("");
    setUploadContent("");
    setUploadedFile(null);
  };

  // Assign a course to a user/role
  const handleIssueAssignment = (e: React.FormEvent) => {
    e.preventDefault();
    if (!assignCourseId) {
      triggerBannerAlert("Please select a training curriculum course.");
      return;
    }

    const targetCourse = courses.find(c => c.id === assignCourseId);
    if (!targetCourse) return;

    const assignmentTarget = assignUser.trim() || (assignRole === "ALL" ? "All Corporate Staff" : `All ${assignRole}s`);
    
    const newAssign: TrainingAssignment = {
      id: `assign-${Date.now()}`,
      courseId: targetCourse.id,
      courseTitle: targetCourse.title,
      assignedToUser: assignmentTarget,
      assignedToRole: assignRole === "ALL" ? "ALL" : (assignRole as UserRole) || undefined,
      status: "PENDING"
    };

    setAssignments(prev => [newAssign, ...prev]);
    saveDocument("infoshield_assignments", newAssign.id, newAssign);
    triggerBannerAlert(`Assigned "${targetCourse.title}" successfully to ${assignmentTarget}.`);
    
    setAssignUser("");
    setAssignCourseId("");
  };

  // Launch course player for a specific assigned course
  const launchCourse = (courseId: string) => {
    const course = courses.find(c => c.id === courseId);
    if (course) {
      setActiveCourseToPlay(course);
      setCurrentQuizAnswers(new Array(course.quiz.length).fill(-1));
      setQuizSubmitted(false);
      setQuizScore(0);
    }
  };

  // Evaluate quiz answers
  const handleQuizSubmit = () => {
    if (!activeCourseToPlay) return;
    
    // Check if all answered
    if (currentQuizAnswers.includes(-1)) {
      triggerBannerAlert("Please select an answer for all security checkpoint questions before submitting.");
      return;
    }

    let score = 0;
    activeCourseToPlay.quiz.forEach((q, idx) => {
      if (currentQuizAnswers[idx] === q.correctIndex) {
        score++;
      }
    });

    setQuizScore(score);
    setQuizSubmitted(true);

    const isPerfect = score === activeCourseToPlay.quiz.length;
    
    // Update active assignment for current user if perfect or completed
    const scoreStr = `${score}/${activeCourseToPlay.quiz.length}`;
    
    setAssignments(prev => {
      return prev.map(a => {
        // Match assignment for this course assigned to this user or their role
        const isMatched = a.courseId === activeCourseToPlay.id && (a.status !== "COMPLETED" || !a.completedAt);
        if (isMatched) {
          const updated: TrainingAssignment = {
            ...a,
            status: isPerfect ? "COMPLETED" : "IN_PROGRESS",
            completedAt: isPerfect ? new Date().toISOString().replace("T", " ").substring(0, 16) : undefined,
            quizScore: scoreStr
          };
          saveDocument("infoshield_assignments", updated.id, updated);
          return updated;
        }
        return a;
      });
    });

    if (isPerfect) {
      triggerBannerAlert(`CONGRATULATIONS: You scored 100% on the "${activeCourseToPlay.title}" quiz! Certification generated.`);
    } else {
      triggerBannerAlert(`Checkpoint feedback: Scored ${scoreStr}. Retake is authorized to achieve 100% compliance.`);
    }
  };

  // Theme support classes
  const c_card = isLight ? "bg-white border border-slate-200 text-slate-800 shadow-sm" : "bg-slate-900/40 border border-slate-800 text-slate-100";
  const c_subcard = isLight ? "bg-slate-100/80 border border-slate-200 text-slate-850" : "bg-slate-950/80 border border-slate-850 text-slate-200";
  const c_input = isLight ? "bg-slate-50 border border-slate-200 text-slate-800 focus:border-cyan-500" : "bg-slate-950 border border-slate-850 text-slate-100 focus:border-cyan-500";
  const c_border = isLight ? "border-slate-200" : "border-slate-800";
  const c_text = isLight ? "text-slate-800" : "text-slate-200";
  const c_muted = isLight ? "text-slate-500 font-sans" : "text-slate-400 font-sans";
  const c_table_header = isLight ? "border-b border-slate-200 bg-slate-100/80 font-mono text-slate-600 uppercase text-[10px]" : "border-b border-slate-800 bg-slate-950/40 font-mono text-slate-400 uppercase text-[10px]";
  const c_table_row = isLight ? "hover:bg-slate-100/50 divide-y divide-slate-100 text-slate-700" : "hover:bg-slate-950/20 divide-y divide-slate-850 text-slate-300";

  return (
    <div className="space-y-6">
      
      {/* Top Main Heading block */}
      <div className={`p-5 rounded-xl border flex flex-wrap justify-between items-center gap-4 ${c_card}`}>
        <div>
          <h2 className={`text-xl font-bold flex items-center gap-2 ${isLight ? "text-slate-900" : "text-slate-100"}`}>
            <GraduationCap className="h-5.5 w-5.5 text-cyan-500 animate-pulse" /> Corporate Security Awareness & Training
          </h2>
          <p className="text-xs text-slate-500 mt-1">
            Conduct, assign, and review professional cybersecurity training. Build secure habits to protect corporate endpoints.
          </p>
        </div>

        {/* Sub-tab switcher */}
        <div className={`flex p-1 rounded-xl border shadow-inner ${isLight ? "bg-slate-100 border-slate-200" : "bg-slate-950/20 border-slate-800/60"}`}>
          <button
            onClick={() => setActiveSubTab("my-courses")}
            className={`px-4 py-2 rounded-lg text-xs font-mono font-bold transition cursor-pointer flex items-center gap-1.5 ${
              activeSubTab === "my-courses"
                ? isLight ? "bg-cyan-600 text-white shadow-sm font-bold" : "bg-cyan-500 text-slate-950 shadow-sm"
                : isLight ? "text-slate-500 hover:text-slate-800" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <BookOpen className="h-3.5 w-3.5" /> My Assignments
          </button>
          
          <button
            onClick={() => setActiveSubTab("catalog")}
            className={`px-4 py-2 rounded-lg text-xs font-mono font-bold transition cursor-pointer flex items-center gap-1.5 ${
              activeSubTab === "catalog"
                ? isLight ? "bg-cyan-600 text-white shadow-sm font-bold" : "bg-cyan-500 text-slate-950 shadow-sm"
                : isLight ? "text-slate-500 hover:text-slate-800" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <UploadCloud className="h-3.5 w-3.5" /> Manage Curriculum
          </button>

          <button
            onClick={() => setActiveSubTab("campaigns")}
            className={`px-4 py-2 rounded-lg text-xs font-mono font-bold transition cursor-pointer flex items-center gap-1.5 ${
              activeSubTab === "campaigns"
                ? isLight ? "bg-cyan-600 text-white shadow-sm font-bold" : "bg-cyan-500 text-slate-950 shadow-sm"
                : isLight ? "text-slate-500 hover:text-slate-800" : "text-slate-400 hover:text-slate-200"
            }`}
          >
            <Users className="h-3.5 w-3.5" /> Campaigns & Audit
          </button>
        </div>
      </div>

      {/* KPI Dashboard Row */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
        <div className={`p-5 rounded-xl border flex items-center justify-between ${c_card}`}>
          <div>
            <span className="text-[10px] font-mono font-bold uppercase text-slate-400">Campaign Assignments</span>
            <h3 className="text-3xl font-extrabold text-cyan-500 mt-1.5">{totalAssigned}</h3>
            <span className="text-[10px] text-slate-500 block mt-1">Sustained training pipeline</span>
          </div>
          <div className="h-10 w-10 rounded-full bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
            <Users className="h-5 w-5" />
          </div>
        </div>

        <div className={`p-5 rounded-xl border flex items-center justify-between ${c_card}`}>
          <div>
            <span className="text-[10px] font-mono font-bold uppercase text-slate-400">Completed Courses</span>
            <h3 className="text-3xl font-extrabold text-emerald-400 mt-1.5">{completedCount}</h3>
            <span className="text-[10px] text-slate-500 block mt-1">Fully vetted compliance credentials</span>
          </div>
          <div className="h-10 w-10 rounded-full bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
            <CheckCircle2 className="h-5 w-5" />
          </div>
        </div>

        <div className={`p-5 rounded-xl border flex items-center justify-between ${c_card}`}>
          <div>
            <span className="text-[10px] font-mono font-bold uppercase text-slate-400">Compliance Pass Rate</span>
            <h3 className={`text-3xl font-extrabold mt-1.5 ${
              trainingComplianceRate > 80 ? "text-emerald-400" : "text-amber-400"
            }`}>{trainingComplianceRate}%</h3>
            <span className="text-[10px] text-slate-500 block mt-1">SOC-2 readiness score</span>
          </div>
          <div className="h-10 w-10 rounded-full bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
            <Award className="h-5 w-5 text-cyan-500" />
          </div>
        </div>
      </div>

      {/* Main interactive player if a course is currently launched */}
      {activeCourseToPlay && (
        <div className={`p-6 rounded-xl border-2 space-y-6 relative overflow-hidden ${isLight ? "border-cyan-500/40 bg-cyan-50/60" : "border-cyan-500/50 bg-cyan-950/10"}`}>
          <div className="absolute top-0 right-0 h-24 w-24 bg-cyan-500/5 rounded-full blur-xl pointer-events-none" />
          
          <div className="flex justify-between items-start gap-4">
            <div className="flex items-center gap-3">
              <span className="bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 font-mono text-[9px] font-bold px-2 py-0.5 rounded-full">
                {activeCourseToPlay.category}
              </span>
              <span className="text-slate-450 font-mono text-[10px] flex items-center gap-1">
                <Clock className="h-3 w-3 text-cyan-500" /> {activeCourseToPlay.estimatedMinutes} mins
              </span>
            </div>
            <button
              onClick={() => setActiveCourseToPlay(null)}
              className={`p-1.5 rounded-lg transition cursor-pointer ${isLight ? "hover:bg-slate-200 text-slate-500 hover:text-slate-800" : "hover:bg-slate-800 text-slate-400 hover:text-slate-200"}`}
              title="Close Player"
            >
              <X className="h-4.5 w-4.5" />
            </button>
          </div>

          <div>
            <h3 className={`text-lg font-bold flex items-center gap-2 ${isLight ? "text-slate-900" : "text-slate-100"}`}>
              <Play className="h-4.5 w-4.5 text-cyan-500 fill-cyan-500" /> Active Course Player: {activeCourseToPlay.title}
            </h3>
            <p className={`text-xs mt-1 ${isLight ? "text-slate-600" : "text-slate-400"}`}>{activeCourseToPlay.description}</p>
          </div>

          {/* Simulated File Material Attachment Badge */}
          {activeCourseToPlay.materialUrl && (
            <div className={`p-3.5 rounded-lg border flex items-center justify-between ${isLight ? "bg-white border-slate-200 text-slate-800" : "bg-slate-950/60 border-slate-850"}`}>
              <div className="flex items-center gap-2.5">
                <FileText className="h-4.5 w-4.5 text-cyan-400 shrink-0" />
                <div>
                  <span className={`text-xs font-mono font-bold block ${isLight ? "text-slate-800" : "text-slate-200"}`}>{activeCourseToPlay.materialUrl}</span>
                  <span className="text-[10px] text-slate-500 block">Uploaded curriculum training handbook (Simulated Asset)</span>
                </div>
              </div>
              <span className="text-[9px] font-mono font-bold uppercase px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 border border-emerald-500/20">
                ACTIVE ATTACHMENT
              </span>
            </div>
          )}

          {/* Module Content Reader Panel */}
          <div className={`p-5 rounded-xl border max-h-[320px] overflow-y-auto font-sans text-xs leading-relaxed space-y-4 ${isLight ? "border-slate-200 bg-white text-slate-700" : "border-slate-800 bg-slate-950/50 text-slate-300"}`}>
            {activeCourseToPlay.content.split("\n\n").map((para, pIdx) => {
              if (para.startsWith("###")) {
                return (
                  <h4 key={pIdx} className={`text-xs font-bold font-mono uppercase tracking-tight mt-3 ${isLight ? "text-cyan-700" : "text-cyan-400"}`}>
                    {para.replace("###", "").trim()}
                  </h4>
                );
              }
              if (para.startsWith("-")) {
                return (
                  <ul key={pIdx} className={`list-disc pl-5 space-y-1 ${isLight ? "text-slate-600" : "text-slate-300"}`}>
                    {para.split("\n").map((li, liIdx) => (
                      <li key={liIdx}>{li.replace("-", "").trim()}</li>
                    ))}
                  </ul>
                );
              }
              return <p key={pIdx}>{para}</p>;
            })}
          </div>

          {/* Knowledge Checkpoint Section */}
          <div className={`border-t pt-5 space-y-4 ${c_border}`}>
            <h4 className={`text-xs font-bold font-mono uppercase tracking-widest flex items-center gap-1.5 ${isLight ? "text-cyan-700" : "text-cyan-400"}`}>
              <Sparkles className="h-3.5 w-3.5" /> Compliance Knowledge Checkpoint
            </h4>

            <div className="space-y-5">
              {activeCourseToPlay.quiz.map((q, qIdx) => (
                <div key={qIdx} className={`p-4 rounded-xl border space-y-3 ${isLight ? "border-slate-200 bg-slate-50/50" : "border-slate-850 bg-slate-950/20"}`}>
                  <p className={`text-xs font-medium ${isLight ? "text-slate-850" : "text-slate-200"}`}>
                    {qIdx + 1}. {q.question}
                  </p>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-2.5">
                    {q.options.map((opt, optIdx) => {
                      const isSelected = currentQuizAnswers[qIdx] === optIdx;
                      const isCorrect = optIdx === q.correctIndex;
                      
                      let optionStyle = isLight 
                        ? "border-slate-200 hover:border-slate-300 bg-white text-slate-700" 
                        : "border-slate-800 hover:border-slate-700 bg-slate-950/30 text-slate-300";
                      if (isSelected) {
                        optionStyle = isLight 
                          ? "border-cyan-500 bg-cyan-50/40 text-cyan-700 font-semibold" 
                          : "border-cyan-500 bg-cyan-950/20 text-cyan-400 font-semibold";
                      }
                      if (quizSubmitted) {
                        if (isCorrect) {
                          optionStyle = isLight 
                            ? "border-emerald-500 bg-emerald-50 text-emerald-700 font-bold" 
                            : "border-emerald-500 bg-emerald-950/20 text-emerald-400 font-bold";
                        } else if (isSelected) {
                          optionStyle = isLight 
                            ? "border-red-400 bg-red-50 text-red-600 line-through" 
                            : "border-red-500 bg-red-950/20 text-red-400 line-through";
                        } else {
                          optionStyle = isLight 
                            ? "border-slate-200 bg-slate-100/50 text-slate-450 opacity-60" 
                            : "border-slate-850 bg-slate-950/10 text-slate-500 opacity-60";
                        }
                      }

                      return (
                        <button
                          key={optIdx}
                          disabled={quizSubmitted}
                          onClick={() => {
                            const updated = [...currentQuizAnswers];
                            updated[qIdx] = optIdx;
                            setCurrentQuizAnswers(updated);
                          }}
                          className={`p-3 rounded-lg border text-left text-xs transition cursor-pointer flex items-start gap-2.5 ${optionStyle}`}
                        >
                          <span className={`font-mono text-[10px] font-bold h-4 w-4 rounded-full flex items-center justify-center shrink-0 ${isLight ? "bg-slate-200 text-slate-700" : "bg-slate-800 text-slate-300"}`}>
                            {String.fromCharCode(65 + optIdx)}
                          </span>
                          <span>{opt}</span>
                        </button>
                      );
                    })}
                  </div>
                  {quizSubmitted && currentQuizAnswers[qIdx] !== q.correctIndex && (
                    <p className="text-[10px] text-red-400 font-mono mt-1">
                      ✗ Incorrect. Achieving 100% security hygiene requires full knowledge validation.
                    </p>
                  )}
                  {quizSubmitted && currentQuizAnswers[qIdx] === q.correctIndex && (
                    <p className="text-[10px] text-emerald-400 font-mono mt-1">
                      ✓ Correct. Control objective verified successfully.
                    </p>
                  )}
                </div>
              ))}
            </div>

            {/* Submissions Action bar */}
            <div className="flex justify-between items-center gap-4 flex-wrap">
              {!quizSubmitted ? (
                <button
                  onClick={handleQuizSubmit}
                  className="bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-mono font-extrabold px-6 py-2.5 rounded text-xs transition cursor-pointer flex items-center gap-1.5 shadow-md"
                >
                  Submit Security Checkpoint Answers
                </button>
              ) : (
                <div className="flex items-center gap-3 flex-wrap">
                  <div className={`px-4 py-2 rounded-lg text-xs font-mono font-bold ${
                    quizScore === activeCourseToPlay.quiz.length 
                      ? "bg-emerald-500/10 text-emerald-400 border border-emerald-500/20" 
                      : "bg-amber-500/10 text-amber-400 border border-amber-500/20"
                  }`}>
                    SCORE RECEIVED: {quizScore} / {activeCourseToPlay.quiz.length} ({Math.round((quizScore / activeCourseToPlay.quiz.length) * 100)}%)
                  </div>

                  {quizScore === activeCourseToPlay.quiz.length ? (
                    <span className="text-emerald-400 font-mono text-[11px] font-bold">
                      ✓ Compliance requirement completed!
                    </span>
                  ) : (
                    <button
                      onClick={() => {
                        setQuizSubmitted(false);
                        setCurrentQuizAnswers(new Array(activeCourseToPlay.quiz.length).fill(-1));
                      }}
                      className="bg-amber-600 hover:bg-amber-500 text-slate-950 font-mono font-bold px-4 py-2 rounded text-xs transition cursor-pointer"
                    >
                      Retry Knowledge Test
                    </button>
                  )}
                </div>
              )}

              <button
                onClick={() => setActiveCourseToPlay(null)}
                className="text-xs text-slate-400 hover:text-slate-200 transition cursor-pointer font-mono"
              >
                Close course player
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Subtab 1: My Courses / Playable Sandbox */}
      {activeSubTab === "my-courses" && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            
            {/* List of courses current user can take */}
            <div className={`p-5 rounded-xl border ${c_card}`}>
              <h3 className="font-bold text-sm uppercase font-mono tracking-tight mb-4 flex items-center gap-2">
                <BookOpen className="h-4.5 w-4.5 text-cyan-500" /> Assigned Awareness Curriculum
              </h3>
              
              <div className="space-y-4">
                {courses.map((course) => {
                  // Find assignment state for this course if active
                  const isCompleted = assignments.some(
                    a => a.courseId === course.id && a.status === "COMPLETED"
                  );
                  const isPending = assignments.some(
                    a => a.courseId === course.id && a.status === "PENDING"
                  );
                  
                  return (
                    <div
                      key={course.id}
                      className={`p-4 rounded-xl border transition ${
                        isCompleted 
                          ? isLight ? "bg-emerald-50/50 border-emerald-500/20" : "bg-emerald-500/5 border-emerald-500/10" 
                          : activeCourseToPlay?.id === course.id
                          ? "border-cyan-500 bg-cyan-500/5"
                          : c_subcard
                      }`}
                    >
                      <div className="flex justify-between items-start gap-4">
                        <div>
                          <div className="flex items-center gap-2">
                            <span className={`text-[10px] font-mono font-bold px-2 py-0.5 rounded ${isLight ? "bg-slate-200 text-cyan-800" : "bg-slate-950/40 text-cyan-400"}`}>
                              {course.category}
                            </span>
                            <span className="text-[9.5px] font-mono text-slate-500 flex items-center gap-1">
                              <Clock className="h-3 w-3" /> {course.estimatedMinutes} mins
                            </span>
                          </div>
                          <h4 className={`text-xs font-bold mt-2 font-sans leading-snug ${isLight ? "text-slate-900" : "text-slate-200"}`}>
                            {course.title}
                          </h4>
                          <p className={`text-[11px] mt-1 leading-relaxed ${isLight ? "text-slate-600" : "text-slate-400"}`}>
                            {course.description}
                          </p>
                        </div>

                        <div className="text-right shrink-0">
                          {isCompleted ? (
                            <span className="text-[10px] font-mono font-bold text-emerald-400 bg-emerald-500/10 border border-emerald-500/20 px-2.5 py-1 rounded-full uppercase">
                              ✓ Completed
                            </span>
                          ) : (
                            <button
                              onClick={() => launchCourse(course.id)}
                              className="bg-cyan-500 hover:bg-cyan-400 text-slate-950 font-mono font-extrabold text-[10px] uppercase px-3 py-1.5 rounded transition cursor-pointer flex items-center gap-1"
                            >
                              Take Course
                            </button>
                          )}
                        </div>
                      </div>

                      {/* Course verification metadata & action button */}
                      {isCompleted && (
                        <div className="mt-3.5 pt-3 border-t border-slate-800/40 flex items-center justify-between">
                          <span className="text-[9.5px] text-slate-500 font-mono">
                            Cred verified. Perfect test score logged.
                          </span>
                          
                          <button
                            onClick={() => {
                              const match = assignments.find(
                                a => a.courseId === course.id && a.status === "COMPLETED"
                              );
                              if (match) {
                                setSelectedCertificateAssign(match);
                              } else {
                                // Fallback fake assignment to satisfy prompt preview
                                setSelectedCertificateAssign({
                                  id: "assign-fallback",
                                  courseId: course.id,
                                  courseTitle: course.title,
                                  assignedToUser: currentUser?.name || "Corporate Employee",
                                  status: "COMPLETED",
                                  completedAt: new Date().toISOString().replace("T", " ").substring(0, 16),
                                  quizScore: "3/3 (100%)"
                                });
                              }
                            }}
                            className="text-cyan-400 hover:text-cyan-300 text-[10px] font-mono font-bold flex items-center gap-1.5 underline cursor-pointer"
                          >
                            <Award className="h-3.5 w-3.5" /> View Security Credential
                          </button>
                        </div>
                      )}
                    </div>
                  );
                })}
              </div>
            </div>

            {/* Information awareness overview tips */}
            <div className="space-y-6">
              <div className={`p-5 rounded-xl border ${c_card}`}>
                <h3 className="font-bold text-sm uppercase font-mono tracking-tight mb-3 flex items-center gap-2">
                  <Sparkles className="h-4.5 w-4.5 text-cyan-500" /> Active Threat Advisory
                </h3>
                <p className="text-xs text-slate-400 leading-relaxed mb-4">
                  The SOC team detected elevated brute force indicators targeting our staging clusters this week. Review your Multi-Factor Authentication setups and ensure credentials are secure.
                </p>

                  <div className={`p-4 rounded-xl space-y-3.5 ${isLight ? "bg-slate-50 border border-slate-200" : "bg-slate-950/40 border border-slate-800"}`}>
                    <div className="flex gap-3">
                      <span className="h-6 w-6 rounded-full bg-cyan-500/10 text-cyan-500 border border-cyan-500/20 flex items-center justify-center text-xs font-mono shrink-0">1</span>
                      <div>
                        <span className={`text-xs font-bold block ${isLight ? "text-slate-900" : "text-slate-200"}`}>Report instantly</span>
                        <span className={`text-[11px] mt-0.5 block leading-relaxed ${isLight ? "text-slate-600" : "text-slate-400"}`}>If you receive an unknown file attachment, do not execute it. Forward it to security audits.</span>
                      </div>
                    </div>

                    <div className="flex gap-3">
                      <span className="h-6 w-6 rounded-full bg-cyan-500/10 text-cyan-500 border border-cyan-500/20 flex items-center justify-center text-xs font-mono shrink-0">2</span>
                      <div>
                        <span className={`text-xs font-bold block ${isLight ? "text-slate-900" : "text-slate-200"}`}>Do not trust urgent request tags</span>
                        <span className={`text-[11px] mt-0.5 block leading-relaxed ${isLight ? "text-slate-600" : "text-slate-400"}`}>Administrators or Executives will never request your private password keys to execute patches.</span>
                      </div>
                    </div>
                  </div>
              </div>

              {/* Training certificate widget preview */}
              <div className={`p-5 rounded-xl border relative overflow-hidden ${c_card}`}>
                <div className="absolute top-0 right-0 h-28 w-28 bg-emerald-500/5 rounded-full blur-xl" />
                <h3 className="font-bold text-sm uppercase font-mono tracking-tight mb-2.5">
                  Corporate Compliance Badge
                </h3>
                <p className="text-xs text-slate-400 mb-4">
                  Employees scoring 100% on security curriculum awareness quizzes are awarded official verified digital compliance certificates.
                </p>
                <div className={`border border-dashed p-4 rounded-xl text-center ${isLight ? "border-slate-300 bg-slate-50" : "border-slate-800 bg-slate-950/20"}`}>
                  <Award className="h-8 w-8 text-emerald-500 mx-auto animate-bounce mb-2" />
                  <span className={`text-xs font-mono block font-bold ${isLight ? "text-slate-900" : "text-slate-200"}`}>InfoShield Security Champion Badge</span>
                  <span className="text-[10px] text-slate-500 mt-1 block">Successfully achieve 3 Completed courses to gain the certification status.</span>
                </div>
              </div>
            </div>

          </div>
        </div>
      )}

      {/* Subtab 2: Manage Curriculum / Custom Course Upload Form */}
      {activeSubTab === "catalog" && (
        <div className="space-y-6">
          
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
            
            {/* Left Column: Form to upload curriculum material and create custom course */}
            <div className="lg:col-span-7 space-y-6">
              <div className={`p-5 rounded-xl border ${c_card}`}>
                <div className="flex justify-between items-center flex-wrap gap-3 mb-1">
                  <h3 className="font-bold text-sm uppercase font-mono tracking-tight flex items-center gap-2">
                    <UploadCloud className="h-4.5 w-4.5 text-cyan-500" /> Create Security Module & Upload Materials
                  </h3>
                  <span className="bg-cyan-500/10 border border-cyan-500/30 text-cyan-400 text-[10px] font-mono px-2 py-0.5 rounded-full uppercase font-semibold">
                    ADMIN DESK
                  </span>
                </div>
                <p className="text-xs text-slate-500 mb-6">
                  Compose custom security awareness training modules and associate simulated files (PDF / Slides) or custom guidelines directly to corporate nodes.
                </p>

                {/* Form starts */}
                <form onSubmit={handleCreateCourse} className="space-y-4">
                  
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <label className="text-[11px] font-mono text-slate-400 uppercase font-semibold">Course Title *</label>
                      <input
                        type="text"
                        required
                        value={uploadTitle}
                        onChange={(e) => setUploadTitle(e.target.value)}
                        placeholder="e.g. Remote Office Endpoint Audits"
                        className={`w-full rounded px-3 py-2 text-xs focus:outline-none ${c_input}`}
                      />
                    </div>

                    <div className="grid grid-cols-2 gap-3">
                      <div className="space-y-1.5">
                        <label className="text-[11px] font-mono text-slate-400 uppercase font-semibold">Category</label>
                        <select
                          value={uploadCategory}
                          onChange={(e) => setUploadCategory(e.target.value as any)}
                          className={`w-full rounded px-2.5 py-2 text-xs focus:outline-none ${c_input}`}
                        >
                          <option value="PHISHING">Phishing</option>
                          <option value="MFA">MFA Hygiene</option>
                          <option value="COMPLIANCE">Compliance</option>
                          <option value="INCIDENT_RESPONSE">Incident Resp</option>
                          <option value="CUSTOM">Custom General</option>
                        </select>
                      </div>

                      <div className="space-y-1.5">
                        <label className="text-[11px] font-mono text-slate-400 uppercase font-semibold">Duration (Mins)</label>
                        <input
                          type="number"
                          min="1"
                          max="120"
                          value={uploadMinutes}
                          onChange={(e) => setUploadMinutes(Number(e.target.value))}
                          className={`w-full rounded px-3 py-2 text-xs focus:outline-none ${c_input}`}
                        />
                      </div>
                    </div>
                  </div>

                  <div className="space-y-1.5">
                    <label className="text-[11px] font-mono text-slate-400 uppercase font-semibold">Brief Description</label>
                    <input
                      type="text"
                      value={uploadDescription}
                      onChange={(e) => setUploadDescription(e.target.value)}
                      placeholder="e.g. A quick introductory guide to keeping home routers secure."
                      className={`w-full rounded px-3 py-2 text-xs focus:outline-none ${c_input}`}
                    />
                  </div>

                  {/* Drag-and-drop file upload simulator */}
                  <div className="space-y-1.5">
                    <label className="text-[11px] font-mono text-slate-400 uppercase font-semibold">
                      Curriculum Attachment Handbook (.PDF / .PPTX)
                    </label>
                    
                    <div
                      onDragEnter={handleDrag}
                      onDragOver={handleDrag}
                      onDragLeave={handleDrag}
                      onDrop={handleDrop}
                      className={`border-2 border-dashed rounded-xl p-6 text-center transition cursor-pointer relative ${
                        dragActive 
                          ? "border-cyan-500 bg-cyan-500/10" 
                          : uploadedFile 
                          ? "border-emerald-500/50 bg-emerald-500/5" 
                          : isLight ? "border-slate-300 hover:border-slate-400 bg-slate-50/50" : "border-slate-800 hover:border-slate-700 bg-slate-950/20"
                      }`}
                    >
                      <input
                        type="file"
                        id="course-file-upload"
                        onChange={handleFileChange}
                        className="absolute inset-0 w-full h-full opacity-0 cursor-pointer"
                        accept=".pdf,.pptx,.docx,.txt"
                      />
                      
                      {!uploadedFile ? (
                        <div className="space-y-2">
                          <FileUp className="h-8 w-8 text-cyan-500 mx-auto animate-pulse" />
                          <p className={`text-xs font-semibold ${isLight ? "text-slate-800" : "text-slate-200"}`}>
                            Drag & drop training PDF / presentation slide deck here
                          </p>
                          <p className="text-[10px] text-slate-500">
                            or click to browse local folders (Max limit: 25MB)
                          </p>
                        </div>
                      ) : (
                        <div className="space-y-1.5">
                          <CheckCircle2 className="h-8 w-8 text-emerald-400 mx-auto" />
                          <p className="text-xs font-semibold text-emerald-400">
                            File successfully analyzed & mapped to curriculum!
                          </p>
                          <p className="text-[11px] text-slate-300 font-mono">
                            {uploadedFile.name} ({uploadedFile.size})
                          </p>
                          <button
                            type="button"
                            onClick={(e) => {
                              e.preventDefault();
                              e.stopPropagation();
                              setUploadedFile(null);
                            }}
                            className="text-[10px] text-red-400 font-mono underline hover:text-red-300 cursor-pointer block mx-auto mt-2"
                          >
                            Remove and select different file
                          </button>
                        </div>
                      )}
                    </div>
                  </div>

                  {/* Detailed Study Content editor */}
                  <div className="space-y-1.5">
                    <label className="text-[11px] font-mono text-slate-400 uppercase font-semibold flex items-center justify-between">
                      <span>Course Study Content (Markdown Supported) *</span>
                      <span className="text-[9px] text-slate-500 italic">e.g. Use ### for chapter headings</span>
                    </label>
                    <textarea
                      required
                      rows={5}
                      value={uploadContent}
                      onChange={(e) => setUploadContent(e.target.value)}
                      placeholder="### MODULE 1: Title&#10;Write the actual paragraphs and guidelines here..."
                      className={`w-full rounded px-3 py-2 text-xs font-mono focus:outline-none ${c_input}`}
                    />
                  </div>

                  {/* Live Checkpoint Question 1 Creator */}
                  <div className="p-4 rounded-xl border border-slate-850 bg-slate-950/20 space-y-3">
                    <span className="text-[10px] font-mono font-bold text-cyan-400 uppercase block">
                      Custom Security Checkpoint Creator
                    </span>
                    
                    <div className="space-y-3">
                      <div className="space-y-1">
                        <span className="text-[10px] text-slate-400 block font-semibold">Checkpoint Question:</span>
                        <input
                          type="text"
                          value={customQuestion}
                          onChange={(e) => setCustomQuestion(e.target.value)}
                          className={`w-full rounded px-3 py-2 text-xs focus:outline-none ${c_input}`}
                        />
                      </div>

                      <div className="grid grid-cols-1 md:grid-cols-2 gap-2">
                        {customOptions.map((opt, oIdx) => (
                          <div key={oIdx} className="flex items-center gap-2">
                            <span className="text-[10px] font-mono text-slate-500">{oIdx + 1}.</span>
                            <input
                              type="text"
                              value={opt}
                              onChange={(e) => {
                                const copy = [...customOptions];
                                copy[oIdx] = e.target.value;
                                setCustomOptions(copy);
                              }}
                              className={`flex-1 rounded px-2.5 py-1 text-xs focus:outline-none ${c_input}`}
                            />
                            <input
                              type="radio"
                              name="correct-answer"
                              checked={correctOptionIndex === oIdx}
                              onChange={() => setCorrectOptionIndex(oIdx)}
                              className="accent-cyan-500 cursor-pointer"
                              title="Mark as correct"
                            />
                          </div>
                        ))}
                      </div>
                      <p className="text-[9.5px] text-slate-500 italic">
                        * Use the radio buttons on the right of options to select the correct answers key.
                      </p>
                    </div>
                  </div>

                  {/* Submission triggers */}
                  <button
                    type="submit"
                    className="w-full bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-mono font-extrabold py-2.5 rounded text-xs transition cursor-pointer flex items-center justify-center gap-1.5 shadow-md"
                  >
                    <Plus className="h-4 w-4" /> Publish Security Course & Open Campaign
                  </button>

                </form>
              </div>
            </div>

            {/* Right Column: Active catalog listing & Management actions */}
            <div className="lg:col-span-5 space-y-6">
              <div className={`p-5 rounded-xl border ${c_card}`}>
                <h3 className="font-bold text-sm uppercase font-mono tracking-tight mb-4 flex items-center gap-2">
                  <BookOpen className="h-4.5 w-4.5 text-cyan-500" /> Active Course Catalog ({courses.length})
                </h3>
                
                <div className="space-y-4">
                  {courses.map((course) => (
                    <div key={course.id} className={`p-4 rounded-xl border space-y-3 ${isLight ? "bg-slate-50/80 border-slate-200" : "bg-slate-950/20 border-slate-800"}`}>
                      <div className="flex justify-between items-start gap-4">
                        <div>
                          <span className={`text-[9px] font-mono font-bold px-2 py-0.5 rounded border ${isLight ? "bg-slate-200 border-slate-300 text-cyan-800" : "bg-slate-900 border-slate-800 text-cyan-400"}`}>
                            {course.category}
                          </span>
                          <h4 className={`text-xs font-bold mt-2 font-sans ${isLight ? "text-slate-900" : "text-slate-200"}`}>{course.title}</h4>
                        </div>
                        
                        {/* Only allow deleting custom uploaded courses */}
                        {course.id.startsWith("course-custom") && (
                          <button
                            onClick={() => {
                              setCourses(prev => prev.filter(c => c.id !== course.id));
                              deleteDocument("infoshield_courses", course.id);
                              triggerBannerAlert(`Deleted custom module: "${course.title}"`);
                            }}
                            className="p-1 text-slate-500 hover:text-red-400 transition cursor-pointer"
                            title="Delete custom module"
                          >
                            <Trash2 className="h-4 w-4" />
                          </button>
                        )}
                      </div>

                      <p className="text-[11px] text-slate-400 line-clamp-2 leading-relaxed">
                        {course.description}
                      </p>

                      <div className="pt-2.5 border-t border-slate-800/60 flex justify-between items-center text-[9.5px] text-slate-500 font-mono">
                        <span>Duration: {course.estimatedMinutes} mins</span>
                        <span>Quiz: {course.quiz.length} Questions</span>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>

          </div>

        </div>
      )}

      {/* Subtab 3: Assignments list & Campaign distribution */}
      {activeSubTab === "campaigns" && (
        <div className="space-y-6">
          
          {/* Quick Assign form row */}
          <div className={`p-5 rounded-xl border ${c_card}`}>
            <h3 className="font-bold text-sm uppercase font-mono tracking-tight mb-4 flex items-center gap-1.5">
              <Send className="h-4 w-4 text-cyan-500" /> Dispatch New Security Training Campaign
            </h3>

            <form onSubmit={handleIssueAssignment} className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
              
              <div className="space-y-1.5">
                <label className="text-[10px] font-mono text-slate-400 uppercase font-semibold">1. Select Course</label>
                <select
                  required
                  value={assignCourseId}
                  onChange={(e) => setAssignCourseId(e.target.value)}
                  className={`w-full rounded px-2.5 py-2 text-xs focus:outline-none ${c_input}`}
                >
                  <option value="">-- Choose Curriculum Course --</option>
                  {courses.map(c => (
                    <option key={c.id} value={c.id}>{c.title}</option>
                  ))}
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-mono text-slate-400 uppercase font-semibold">2. Target Role Group</label>
                <select
                  value={assignRole}
                  onChange={(e) => {
                    setAssignRole(e.target.value as any);
                    if (e.target.value) setAssignUser(""); // reset individual name
                  }}
                  className={`w-full rounded px-2.5 py-2 text-xs focus:outline-none ${c_input}`}
                >
                  <option value="ALL">All Roles (All Staff)</option>
                  <option value="CISO">Chief Info Security Officer (CISO)</option>
                  <option value="SecEngineer">Security Engineers</option>
                  <option value="ComplianceOfficer">Compliance Officers</option>
                  <option value="Auditor">External Auditors</option>
                </select>
              </div>

              <div className="space-y-1.5">
                <label className="text-[10px] font-mono text-slate-400 uppercase font-semibold">Or Specific Employee Name</label>
                <input
                  type="text"
                  value={assignUser}
                  onChange={(e) => {
                    setAssignUser(e.target.value);
                    if (e.target.value) setAssignRole(""); // override role select
                  }}
                  placeholder="e.g. David Sterling (IT Analyst)"
                  className={`w-full rounded px-3 py-2 text-xs focus:outline-none ${c_input}`}
                />
              </div>

              <button
                type="submit"
                className="bg-cyan-600 hover:bg-cyan-500 text-slate-950 font-mono font-extrabold py-2.5 rounded text-xs transition cursor-pointer flex items-center justify-center gap-1.5 shadow-md h-[38px]"
              >
                <Send className="h-3.5 w-3.5" /> Dispatch Campaign
              </button>

            </form>
          </div>

          {/* Table of all active assignments & campaigns */}
          <div className={`rounded-xl overflow-hidden border ${c_card}`}>
            <div className={`p-4 border-b flex justify-between items-center gap-3 ${c_border}`}>
              <h3 className="font-bold text-xs uppercase font-mono text-slate-200">
                Staff Training Compliance Log
              </h3>
              <span className="text-[10px] text-slate-500 font-mono">
                Real-time GRC continuous verification matrix
              </span>
            </div>

            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse text-xs">
                <thead>
                  <tr className={`${c_table_header}`}>
                    <th className="p-4">Assigned Personnel</th>
                    <th className="p-4">Curriculum Module</th>
                    <th className="p-4">Assigned Target Role</th>
                    <th className="p-4">Compliance Status</th>
                    <th className="p-4">Score Checkpoint</th>
                    <th className="p-4 text-right">Certificate Action</th>
                  </tr>
                </thead>
                <tbody className={`divide-y ${isLight ? "divide-slate-100" : "divide-slate-850"}`}>
                  {assignments.map((assign) => (
                    <tr key={assign.id} className={`${c_table_row} transition`}>
                      <td className={`p-4 font-mono font-bold ${isLight ? "text-slate-800" : "text-slate-200"}`}>
                        {assign.assignedToUser}
                      </td>
                      <td className={`p-4 font-sans font-medium ${isLight ? "text-slate-700" : "text-slate-300"}`}>
                        {assign.courseTitle}
                      </td>
                      <td className="p-4">
                        <span className={`font-mono text-[10px] px-2 py-0.5 rounded border ${isLight ? "bg-slate-100 border-slate-200 text-cyan-800" : "bg-slate-950/40 border-slate-800 text-cyan-400"}`}>
                          {assign.assignedToRole || "Individual Override"}
                        </span>
                      </td>
                      <td className="p-4">
                        <span className={`px-2 py-0.5 rounded font-mono text-[9.5px] font-bold border ${
                          assign.status === "COMPLETED"
                            ? "bg-emerald-500/10 text-emerald-400 border-emerald-500/20"
                            : assign.status === "IN_PROGRESS"
                            ? "bg-amber-500/10 text-amber-400 border-amber-500/20"
                            : "bg-slate-800 text-slate-400 border-slate-700"
                        }`}>
                          {assign.status}
                        </span>
                      </td>
                      <td className="p-4 font-mono text-slate-400">
                        {assign.quizScore || "--"}
                      </td>
                      <td className="p-4 text-right">
                        {assign.status === "COMPLETED" ? (
                          <button
                            onClick={() => setSelectedCertificateAssign(assign)}
                            className="bg-emerald-500/10 hover:bg-emerald-500 border border-emerald-500/25 text-emerald-400 hover:text-slate-950 px-2.5 py-1 rounded transition text-[10px] font-mono font-bold uppercase cursor-pointer flex items-center gap-1.5 ml-auto"
                          >
                            <Award className="h-3.5 w-3.5" /> View Certificate
                          </button>
                        ) : (
                          <span className="text-slate-500 font-mono text-[10px] italic">
                            Awaiting Compliance
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

        </div>
      )}

      {/* =======================================================
          POPUP MODAL: GRC INFORMATION SECURITY CERTIFICATE PREVIEW
          ======================================================= */}
      {selectedCertificateAssign && (
        <div className="fixed inset-0 bg-slate-950/80 backdrop-blur-sm z-50 flex items-center justify-center p-4">
          <div className={`border-2 border-amber-500/40 rounded-2xl max-w-2xl w-full p-8 shadow-2xl space-y-6 relative overflow-hidden ${isLight ? "bg-white" : "bg-slate-900"}`}>
            
            {/* Top Certificate Border Accents */}
            <div className="absolute top-0 inset-x-0 h-1.5 bg-gradient-to-r from-amber-500 via-yellow-400 to-cyan-500" />
            <div className="absolute top-6 right-6 text-amber-500/10 select-none">
              <Award className="h-44 w-44" />
            </div>

            <div className="flex justify-between items-start">
              <div>
                <span className="text-[10px] font-mono text-amber-550 uppercase tracking-widest block font-bold">
                  INFOSHIELD CONTINUOUS GRC CAMPAIGN
                </span>
                <h3 className={`text-xl font-bold font-mono mt-1 ${isLight ? "text-slate-950" : "text-slate-100"}`}>
                  Security Awareness Compliance Certificate
                </h3>
              </div>
              <button
                onClick={() => setSelectedCertificateAssign(null)}
                className={`p-1 rounded-lg transition cursor-pointer ${isLight ? "hover:bg-slate-100 text-slate-500 hover:text-slate-850" : "hover:bg-slate-800 text-slate-400 hover:text-slate-200"}`}
              >
                <X className="h-5 w-5" />
              </button>
            </div>

            {/* Certificate Body Container */}
            <div className={`p-8 rounded-xl border border-amber-500/20 text-center space-y-6 relative ${isLight ? "bg-amber-50/10" : "bg-slate-950"}`}>
              
              {/* Corner certificate graphic accents */}
              <div className="absolute top-2 left-2 border-t-2 border-l-2 border-amber-500/30 h-4 w-4" />
              <div className="absolute top-2 right-2 border-t-2 border-r-2 border-amber-500/30 h-4 w-4" />
              <div className="absolute bottom-2 left-2 border-b-2 border-l-2 border-amber-500/30 h-4 w-4" />
              <div className="absolute bottom-2 right-2 border-b-2 border-r-2 border-amber-500/30 h-4 w-4" />

              <span className="text-[10px] font-mono text-slate-500 block uppercase tracking-widest">
                This certifies that the employee
              </span>

              <h4 className="text-2xl font-extrabold text-amber-550 font-sans tracking-tight">
                {selectedCertificateAssign.assignedToUser.split(" (")[0]}
              </h4>

              <span className="text-[10px] font-mono text-slate-500 block uppercase tracking-widest">
                has successfully audited and validated competency in
              </span>

              <h5 className={`text-base font-bold max-w-md mx-auto ${isLight ? "text-slate-900" : "text-slate-100"}`}>
                {selectedCertificateAssign.courseTitle}
              </h5>

              <p className={`text-[11px] leading-relaxed max-w-md mx-auto font-sans ${isLight ? "text-slate-700" : "text-slate-400"}`}>
                By passing the advanced multiple-choice technical verification quiz with an absolute perfect score of <strong className="text-emerald-550">{selectedCertificateAssign.quizScore || "3/3 (100%)"}</strong>, verifying compliance controls under SOC-2 continuous framework audits.
              </p>

              {/* Certificate Signatures section */}
              <div className={`grid grid-cols-2 gap-6 pt-6 border-t text-left ${isLight ? "border-slate-200" : "border-slate-900"}`}>
                <div>
                  <span className="text-[9px] font-mono text-slate-500 block uppercase">AUTHORIZED BY</span>
                  <span className={`text-xs font-mono font-bold block mt-1 ${isLight ? "text-slate-800" : "text-slate-300"}`}>InfoShield SIEM Engine</span>
                  <span className="text-[9px] text-slate-500 block font-mono">Timestamp: {selectedCertificateAssign.completedAt || new Date().toISOString().substring(0, 10)}</span>
                </div>
                <div className="text-right">
                  <span className="text-[9px] font-mono text-slate-500 block uppercase">VERIFICATION TOKEN</span>
                  <code className={`text-[10px] font-mono block mt-1 truncate ${isLight ? "text-cyan-700" : "text-cyan-400"}`}>
                    SHIELD-{Math.floor(100000 + Math.random() * 900000)}-SEC
                  </code>
                  <span className="text-[9px] text-slate-500 block">Status: Verified Ledger Active</span>
                </div>
              </div>

            </div>

            {/* Certificate Exports Actions */}
            <div className="flex justify-between items-center gap-4 flex-wrap pt-2">
              <span className={`text-[10.5px] font-sans ${isLight ? "text-slate-600" : "text-slate-400"}`}>
                Export to verify regulatory alignment during GRC review.
              </span>
              
              <button
                onClick={() => {
                  triggerBannerAlert(`Successfully exported verified certificate PDF schema for ${selectedCertificateAssign.assignedToUser}.`);
                  setSelectedCertificateAssign(null);
                }}
                className="bg-amber-500 hover:bg-amber-400 text-slate-950 font-mono font-extrabold px-4 py-2 rounded text-xs transition cursor-pointer flex items-center gap-1.5 shadow-md"
              >
                <Download className="h-4 w-4" /> Download Certificate (PDF)
              </button>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}
